const fs = require('fs');
const path = require('path');

const { createBotClient, postToChannel, waitForApproval } = require('../../discord/client');
const { Octokit } = require('@octokit/rest');

/**
 * PM Agent — ephemeral, spawned per project.
 * Responsible for:
 * - Reading estimation history
 * - Building cost estimates
 * - Creating GitHub Issues from spec deliverables
 * - Setting up Discord project channels
 * - Managing the project backlog
 */

class PMAgent {
  constructor(spec, projectChannels) {
    this.spec = spec;
    this.projectChannels = projectChannels;
    this.client = createBotClient(process.env.PM_TOKEN);
    this.octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
    this.owner = process.env.GITHUB_OWNER;
    this.repo = process.env.GITHUB_REPO;
    this.ollamaUrl = process.env.OLLAMA_BASE_URL || 'http://127.0.0.1:11434';
    this.anthropicKey = process.env.ANTHROPIC_API_KEY;
    this.model = process.env.MANAGER_MODEL || (this.anthropicKey ? 'claude-sonnet-4-6' : 'llama3.1:8b');
    this.projectRepo = null;

    this.ready = new Promise((resolve) => {
      this.client.once('clientReady', () => {
        console.log(`[PM] Online as ${this.client.user.tag}`);
        resolve();
      });
    });
  }

  /**
   * Main entry point — runs the full PM setup sequence.
   */
  async run() {
    await this.ready;
    await this.postToManagers(`📋 PM Agent online for project: **${this.spec.projectName}**`);

    try {
      const history = await this.readEstimationHistory();
      const estimate = await this.buildEstimate(history);
      this.estimate = estimate;
      const approved = await this.requestEstimateApproval(estimate);

      if (!approved) {
        await this.postToManagers(`❌ Cost estimate rejected. Awaiting revised spec from Director.`);
        return;
      }

      const projectRepo = await this.createProjectRepo();
      this.projectRepo = projectRepo;

      await this.setupGitHubLabels();

      console.log('[PM] Creating Issues...');
      await this.createIssues();
      console.log('[PM] Issues created.');

      await this.postToManagers(`✅ Project setup complete. Issues created. Workers can begin.`);

    } catch (err) {
      console.error('[PM] Fatal error in run():', err.message);
      console.error(err.stack);
    }
  }

  /**
   * Creates a new GitHub repo for the project.
   * @returns {object} projectRepo
   */
  async createProjectRepo() {
    const repoName = this.spec.projectName;

    try {
      const { data: repo } = await this.octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: `Generated by agent-dev-team — ${this.spec.brief.desiredOutcome}`,
        private: false,
        auto_init: true
      });

      console.log(`[PM] Project repo created: ${repo.html_url}`);
      await this.postToManagers(`📦 Project repo created: ${repo.html_url}`);

      await this._registerWebhook(repo.owner.login, repo.name);

      return {
        owner: repo.owner.login,
        repo: repo.name,
        url: repo.html_url,
        defaultBranch: repo.default_branch
      };

    } catch (err) {
      if (err.status === 422) {
        console.log(`[PM] Repo already exists: ${repoName}`);
        const { data: repo } = await this.octokit.repos.get({
          owner: this.owner,
          repo: repoName
        });
        return {
          owner: repo.owner.login,
          repo: repo.name,
          url: repo.html_url,
          defaultBranch: repo.default_branch
        };
      }
      throw err;
    }
  }

  /**
   * Reads the estimation history from bessemer-state, falling back to local file.
   * @returns {Promise<object>} history
   */
  async readEstimationHistory() {
    const stateOwner = process.env.BESSEMER_STATE_OWNER || 'usebessemer';
    const stateRepo = process.env.BESSEMER_STATE_REPO || 'bessemer-state';

    try {
      const { data } = await this.octokit.repos.getContent({
        owner: stateOwner,
        repo: stateRepo,
        path: 'estimation-history.json',
      });
      const content = Buffer.from(data.content, 'base64').toString('utf8');
      return JSON.parse(content);
    } catch (err) {
      console.warn('[PM] bessemer-state unreachable, falling back to local history:', err.message);
      const historyPath = path.join(process.cwd(), 'projects', 'estimation-history.json');
      if (!fs.existsSync(historyPath)) return { projects: [] };
      return JSON.parse(fs.readFileSync(historyPath, 'utf8'));
    }
  }

  /**
   * Builds a cost estimate using estimation history when available,
   * falling back to an LLM estimate on cold start.
   * @param {object} history
   * @returns {object} estimate
   */
  async buildEstimate(history) {
    const relevantHistory = history.projects
      .filter(p => p.projectType === this.spec.projectType)
      .slice(-5);

    const hourlyRate = parseInt(process.env.HOURLY_RATE || '20');
    let hours, confidence, notes;

    const MIN_SAMPLE = 3;

    if (relevantHistory.length >= MIN_SAMPLE) {
      const historicalHours = relevantHistory
        .map(p => p.actuals?.hours || p.estimate?.hours || p.hours)
        .filter(h => typeof h === 'number' && h > 0);
      hours = historicalHours.length > 0
        ? Math.round(historicalHours.reduce((sum, h) => sum + h, 0) / historicalHours.length)
        : 8;
      confidence = 'medium';
      notes = `Based on mean of ${relevantHistory.length} past ${this.spec.projectType} projects`;
    } else {
      hours = this.anthropicKey
        ? await this._coldStartEstimateClaude()
        : await this._coldStartEstimateOllama();
      confidence = 'low';
      notes = relevantHistory.length > 0
        ? `Insufficient history (${relevantHistory.length}/${MIN_SAMPLE} required) for ${this.spec.projectType}. LLM estimate only.`
        : `Cold start — no historical data for ${this.spec.projectType || 'this project type'}. LLM estimate only.`;
    }

    const cost = hours * hourlyRate;

    return {
      hours,
      cost,
      currency: process.env.CURRENCY || 'CAD',
      breakdown: this.spec.deliverables?.map(d => ({
        task: d.name,
        hours: Math.ceil(hours / (this.spec.deliverables.length || 1)),
        cost: Math.ceil(cost / (this.spec.deliverables.length || 1))
      })) || [],
      confidence,
      notes
    };
  }

  async _coldStartEstimateOllama() {
    const prompt = `You are a project manager. Given this project: "${this.spec.projectName}" (type: ${this.spec.projectType || 'unknown'}) with ${this.spec.deliverables?.length || 1} deliverables, estimate total development hours. Respond with ONLY a single number between 1 and 100. No other text.`;
    const response = await fetch(`${this.ollamaUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: this.model, prompt, stream: false }),
    });
    if (!response.ok) throw new Error(`Ollama estimate error ${response.status}`);
    const data = await response.json();
    if (!data.response) throw new Error('Ollama returned empty response for estimate');
    return parseInt(data.response.trim().match(/\d+/)?.[0] || '8');
  }

  async _coldStartEstimateClaude() {
    const prompt = `You are a project manager. Given this project: "${this.spec.projectName}" (type: ${this.spec.projectType || 'unknown'}) with ${this.spec.deliverables?.length || 1} deliverables, estimate total development hours. Respond with ONLY a single number between 1 and 100. No other text.`;
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': this.anthropicKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: 16,
        messages: [{ role: 'user', content: prompt }],
      }),
    });
    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      throw new Error(`Claude estimate error ${response.status}: ${err.error?.message || 'unknown'}`);
    }
    const data = await response.json();
    const text = data.content?.find(b => b.type === 'text')?.text || '8';
    return parseInt(text.trim().match(/\d+/)?.[0] || '8');
  }

  /**
   * Posts estimate to #approvals and waits for executive confirmation.
   * @param {object} estimate
   * @returns {boolean} approved
   */
  async requestEstimateApproval(estimate) {
    const approvalsChannel = process.env.DISCORD_CHANNEL_APPROVALS;
    const estimateJson = JSON.stringify(estimate, null, 2);

    const approvalMessage = await this.client.channels
      .fetch(approvalsChannel)
      .then(channel => channel.send(
        `**Cost Estimate — ${this.spec.projectName}**\n\n` +
        `**Total:** ${estimate.cost} ${estimate.currency}\n` +
        `**Hours:** ${estimate.hours}\n` +
        `**Confidence:** ${estimate.confidence}\n\n` +
        `\`\`\`json\n${estimateJson}\n\`\`\`\n\n` +
        `Type \`approve: ${this.spec.projectName}\` to confirm or \`reject: ${this.spec.projectName}\` to decline. (Plain \`approve\`/\`reject\` also works.)`
      ));

    try {
      return await waitForApproval(this.client, approvalMessage.id, approvalsChannel, this.spec.projectName);
    } catch (err) {
      await postToChannel(
        this.client,
        process.env.DISCORD_CHANNEL_ALERTS,
        `⚠️ Cost estimate approval timed out for: ${this.spec.projectName}`
      );
      return false;
    }
  }

  /**
   * Sets up GitHub labels for this project in the agent-dev-team repo.
   */
  async setupGitHubLabels() {
    const labels = [
      { name: `project:${this.spec.projectName}`, color: '0075ca' },
      { name: 'tier:worker', color: 'e4e669' },
      { name: 'tier:manager', color: 'f9d0c4' },
      { name: 'status:backlog', color: 'd93f0b' },
      { name: 'status:in-progress', color: '0052cc' },
      { name: 'status:review', color: 'bfd4f2' },
      { name: 'status:complete', color: '0e8a16' },
      { name: 'status:blocked', color: 'b60205' },
      { name: 'priority:high', color: 'e11d48' },
      { name: 'priority:medium', color: 'f97316' },
      { name: 'priority:low', color: '84cc16' },
    ];

    for (const label of labels) {
      try {
        await this.octokit.issues.createLabel({
          owner: this.projectRepo?.owner || this.owner,
          repo: this.projectRepo?.repo || this.repo,
          name: label.name,
          color: label.color
        });
      } catch (err) {
        if (err.status !== 422) console.error(`[PM] Label error: ${err.message}`);
      }
    }

    await this.postToManagers(`🏷️ GitHub labels created for project: ${this.spec.projectName}`);
  }

  /**
   * Creates GitHub Issues from spec deliverables in the agent-dev-team repo.
   * Each Issue is a complete, self-contained task brief for a worker.
   */
  async createIssues() {
    const { deliverables, projectName, architecture } = this.spec;

    for (const deliverable of deliverables) {
      const body = `## Task Brief

**Project:** ${projectName}
**Project Repo:** ${this.projectRepo?.url || 'TBD'}
**Type:** ${deliverable.type}

## Objective
${deliverable.description}

## Tech Stack
- Language: ${architecture.techStack.language}
- Runtime: ${architecture.techStack.runtime}
- Packages: ${architecture.techStack.packages.join(', ') || 'none'}

## Acceptance Criteria
${deliverable.acceptanceCriteria.map(c => `- [ ] ${c}`).join('\n')}

## Instructions
- Work in the project repo: ${this.projectRepo?.url || 'TBD'}
- Create a branch: \`coder/[issue-number]/${deliverable.name}\`
- Complete all acceptance criteria
- Open a PR when done
- Do not ask for clarification — use your best judgment

## Context
${JSON.stringify(architecture, null, 2)}`;

      const issue = await this.octokit.issues.create({
        owner: this.projectRepo.owner,
        repo: this.projectRepo.repo,
        title: `[${projectName}] ${deliverable.name}`,
        body,
        labels: [
          `project:${projectName}`,
          'tier:worker',
          'status:backlog',
          'priority:medium',
          `type:${deliverable.type}`,
        ]
      });

      await this.postToManagers(`📌 Issue created: #${issue.data.number} — ${deliverable.name}`);
    }
  }

  /**
   * Registers a GitHub webhook on the project repo for issues and pull_request events.
   * No-ops when WEBHOOK_URL or GITHUB_WEBHOOK_SECRET are not set.
   */
  async _registerWebhook(owner, repo) {
    const webhookUrl = process.env.WEBHOOK_URL;
    const webhookSecret = process.env.GITHUB_WEBHOOK_SECRET;
    if (!webhookUrl || !webhookSecret) return;

    try {
      await this.octokit.repos.createWebhook({
        owner,
        repo,
        config: {
          url: `${webhookUrl}/webhooks/github`,
          secret: webhookSecret,
          content_type: 'json',
        },
        events: ['issues', 'pull_request'],
        active: true,
      });
      console.log(`[PM] GitHub webhook registered for ${owner}/${repo}`);
    } catch (err) {
      console.warn(`[PM] Could not register webhook for ${owner}/${repo}: ${err.message}`);
    }
  }

  /**
   * Posts a message to the project's #managers channel.
   * @param {string} content
   */
  async postToManagers(content) {
    await postToChannel(this.client, this.projectChannels.managers, content);
  }

  /**
   * Discards this PM agent — called when project closes.
   */
  async discard() {
    console.log(`[PM] Discarding for project: ${this.spec.projectName}`);
    await this.client.destroy();
  }
}

module.exports = PMAgent;